apply plugin: 'jacoco'

dependencies {
	api project(":modules:product-rest:product-rest-api")

	compileOnly group: "com.liferay.portal", name: "release.portal.api"
	compileOnly project(":modules:product-service:product-service-api")

	testImplementation group: "com.liferay.portal", name: "release.portal.api"
	testImplementation project(":modules:product-service:product-service-api")
	testImplementation project(":modules:product-service:product-service-service")
	testImplementation group: "org.junit.jupiter", name: "junit-jupiter-api", version: "5.10.2"
	testRuntimeOnly group: "org.junit.jupiter", name: "junit-jupiter-engine", version: "5.10.2"
	testImplementation group: "org.mockito", name: "mockito-junit-jupiter", version: "5.12.0"
	testImplementation group: "org.assertj", name: "assertj-core", version: "3.25.3"
}

group = "product.rest"

test {
	jvmArgs(
		"--add-opens=java.base/java.lang=ALL-UNNAMED",
		"--add-opens=java.base/java.lang.invoke=ALL-UNNAMED",
		"--add-opens=java.base/java.util=ALL-UNNAMED"
	)
	useJUnitPlatform()
}

jacoco {
    toolVersion = '0.8.11'
}

jacocoTestReport {
    dependsOn test

    reports {
        html.required = true
        xml.required = false
    }

    afterEvaluate {
        classDirectories.setFrom(
            files(classDirectories.files.collect {
                fileTree(dir: it, exclude: [
                    '**/resource/v1_0/Base*',
                    '**/dto/v1_0/**',
                    '**/graphql/**',
                    '**/jaxrs/**',
                    '**/security/**',
                    '**/resource/v1_0/factory/**',
                    '**/resource/v1_0/OpenAPI*',
                ])
            })
        )
    }
}

jacocoTestCoverageVerification {
    dependsOn jacocoTestReport

    afterEvaluate {
        classDirectories.setFrom(
            files(classDirectories.files.collect {
                fileTree(dir: it, exclude: [
                    '**/resource/v1_0/Base*',
                    '**/dto/v1_0/**',
                    '**/graphql/**',
                    '**/jaxrs/**',
                    '**/security/**',
                    '**/resource/v1_0/factory/**',
                    '**/resource/v1_0/OpenAPI*',
                ])
            })
        )
    }

    violationRules {
        rule {
            limit {
                counter = 'LINE'
                value = 'COVEREDRATIO'
                minimum = 0.70
            }
        }
        rule {
            limit {
                counter = 'BRANCH'
                value = 'COVEREDRATIO'
                minimum = 0.55
            }
        }
    }
}

check.dependsOn jacocoTestCoverageVerification
