apply plugin: 'jacoco'

dependencies {
	api project(":modules:product-service:product-service-api")

	compileOnly group: "com.liferay.portal", name: "release.portal.api"

	testImplementation group: "com.liferay.portal", name: "release.portal.api"
	testImplementation group: "org.junit.jupiter", name: "junit-jupiter-api", version: "5.10.2"
	testRuntimeOnly group: "org.junit.jupiter", name: "junit-jupiter-engine", version: "5.10.2"
	testImplementation group: "org.mockito", name: "mockito-junit-jupiter", version: "5.12.0"
	testImplementation group: "org.assertj", name: "assertj-core", version: "3.25.3"
}

buildService {
	apiDir = "../product-service-api/src/main/java"
	testDir = "../product-service-test/src/testIntegration/java"
}

group = "product.service"

test {
	jvmArgs(
		"--add-opens=java.base/java.lang=ALL-UNNAMED",
		"--add-opens=java.base/java.lang.invoke=ALL-UNNAMED",
		"--add-opens=java.base/java.util=ALL-UNNAMED"
	)
	useJUnitPlatform()
}

jacoco {
	toolVersion = '0.8.11'
}

jacocoTestReport {
	dependsOn test

	reports {
		html.required = true
		xml.required = false
	}

	afterEvaluate {
		classDirectories.setFrom(
			files(classDirectories.files.collect {
				fileTree(dir: it, exclude: [
					'**/service/base/**',
					'**/model/impl/**',
					'**/service/persistence/impl/**',
				])
			})
		)
	}
}

jacocoTestCoverageVerification {
	dependsOn jacocoTestReport

	afterEvaluate {
		classDirectories.setFrom(
			files(classDirectories.files.collect {
				fileTree(dir: it, exclude: [
					'**/service/base/**',
					'**/model/impl/**',
					'**/service/persistence/impl/**',
				])
			})
		)
	}

	violationRules {
		rule {
			limit {
				counter = 'LINE'
				value = 'COVEREDRATIO'
				minimum = 0.75
			}
		}
		rule {
			limit {
				counter = 'BRANCH'
				value = 'COVEREDRATIO'
				minimum = 0.65
			}
		}
	}
}

check.dependsOn jacocoTestCoverageVerification
