configurations {
	portalTestBundle
}

dependencies {
	testIntegrationImplementation group: "com.liferay.portal", name: "release.portal.api"
	testIntegrationImplementation group: "com.liferay.portal", name: "com.liferay.portal.test", version: "24.6.1"
	testIntegrationImplementation group: "com.liferay.portal", name: "com.liferay.portal.test.integration", version: "6.0.36"
	testIntegrationImplementation group: "com.liferay", name: "com.liferay.arquillian.extension.junit.bridge", version: "1.0.21"
	testIntegrationImplementation group: "junit", name: "junit", version: "4.13.2"
	testIntegrationImplementation group: "org.apache.logging.log4j", name: "log4j-core", version: "2.17.2"
	testIntegrationImplementation group: "org.apache.logging.log4j", name: "log4j-api", version: "2.17.2"
	testIntegrationImplementation "biz.aQute.bnd:aQute.libg:6.4.0"
	portalTestBundle group: "com.liferay.portal", name: "com.liferay.portal.test", version: "24.6.1"
	testIntegrationImplementation project(":modules:product-service:product-service-api")
	testIntegrationImplementation project(":modules:product-service:product-service-service")
}

testIntegration {
	dependsOn "syncProductServiceBundles"
	dependsOn "syncPortalTestBundle"

	jvmArgs += ["-Dorg.jboss.logging.provider=jdk"]
}

tasks.register("syncProductServiceBundles", Copy) {
	from(project(":modules:product-service:product-service-api").tasks.named("jar")) {
		rename {
			"product.service.api.jar"
		}
	}

	from(project(":modules:product-service:product-service-service").tasks.named("jar")) {
		rename {
			"product.service.service.jar"
		}
	}

	into file("${rootProject.projectDir}/bundles/osgi/modules")
}

tasks.register("syncPortalTestBundle", Copy) {
	from configurations.portalTestBundle
	into file("${rootProject.projectDir}/bundles/osgi/test")
	rename {
		"com.liferay.portal.test.jar"
	}
}

tasks.named("setUpTestableTomcat") {
	dependsOn "syncProductServiceBundles"
	dependsOn "syncPortalTestBundle"
}

testIntegrationTomcat {
	dir = file("${rootProject.projectDir}/bundles/tomcat")
	liferayHome = file("${rootProject.projectDir}/bundles")
}

configurations.testIntegrationImplementation {
	exclude group: "org.slf4j", module: "slf4j-log4j12"
	exclude group: "log4j", module: "log4j"
}
